// константи для actions для Books
export const REQUEST_BOOKS = 'REQUEST_BOOKS';
export const RECEIVE_BOOKS = 'RECEIVE_BOOKS';
export const ERROR_RECEIVE_BOOKS = 'ERROR_RECEIVE_BOOKS';

export const REQUEST_DELETE_BOOK = 'REQUEST_DELETE_BOOK';
export const SUCCESS_DELETE_BOOK = 'SUCCESS_DELETE_BOOK';
export const ERROR_DELETE_BOOK = 'ERROR_DELETE_BOOK';