server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  application:
    name: library
  config:
    import: optional:consul:/
  cloud:
    consul:
      host: localhost
      port: 8501
      discovery:
        health-check-path: /health
  data:
    mongodb:
      uri: ${mongoUri}
#      uri: mongodb://localhost:27017/library
      auto-index-creation: true

resilience4j:
  circuitbreaker:
    instances:
      services:
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 60
        slow-call-duration-threshold:
          - 2s
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 1

#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      base-path: /
#      exposure:
#        include: "*"