export const REQUEST_BOOK = 'REQUEST_BOOK';
export const RECEIVE_BOOK = 'RECEIVE_BOOK';
export const ERROR_RECEIVE_BOOK = 'ERROR_RECEIVE_BOOK';

export const REQUEST_UPDATE_BOOK = 'REQUEST_UPDATE_BOOK';
export const SUCCESS_UPDATE_BOOK = 'SUCCESS_UPDATE_BOOK';
export const ERROR_UPDATE_BOOK = 'ERROR_UPDATE_BOOK';